In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
# SimpleImputer --->>>>>>> yeh numeric col kalye
# OneHotEncoder --->>>>>>> yeh nominal col kalye
# OrdinalEncoder --->>>>>>> yeh Ordinal col kalye

In [4]:
df = pd.read_csv('covid_toy.csv')

In [5]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [6]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [7]:
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [8]:
df.shape

(100, 6)

In [11]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [14]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [15]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [16]:
df['age'].value_counts()

age
65    4
19    4
34    4
51    3
64    3
20    3
42    3
69    3
82    3
83    3
5     3
49    3
27    3
14    2
73    2
71    2
80    2
38    2
60    2
23    2
75    2
25    2
12    2
47    2
81    2
24    2
10    2
11    2
16    2
31    1
84    1
33    1
13    1
40    1
70    1
26    1
55    1
74    1
15    1
44    1
66    1
18    1
72    1
22    1
50    1
56    1
6     1
54    1
68    1
8     1
48    1
17    1
46    1
59    1
79    1
Name: count, dtype: int64

In [17]:
df['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [18]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [19]:
df.head(1)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No

In [20]:
# age and fever -->>> numeric
# city , gender are nominal 
# cough is ordinal bcz there is strong and mild comparison 
# has_covid is an label col

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [22]:
x_train

    age  gender  fever   cough       city
46   19  Female  101.0    Mild     Mumbai
37   55    Male  100.0    Mild    Kolkata
30   15    Male  101.0    Mild      Delhi
62   56  Female  104.0  Strong  Bangalore
87   47    Male  101.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
41   82    Male    NaN    Mild    Kolkata
57   49  Female   99.0  Strong  Bangalore
70   68  Female  101.0  Strong      Delhi
66   51    Male  104.0    Mild    Kolkata
8    19  Female  100.0  Strong  Bangalore

[80 rows x 5 columns]

# without col transformer

In [23]:
# adding simple imputer to fever col
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])

# also the test data
x_test_fever = si.fit_transform(x_test[['fever']])
                                 
x_train_fever.shape

(80, 1)

In [24]:
x_train_fever

array([[101.        ],
       [100.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [104.        ],
       [102.        ],
       [102.        ],
       [100.        ],
       [102.        ],
       [104.        ],
       [ 98.        ],
       [100.        ],
       [ 99.        ],
       [101.        ],
       [100.        ],
       [100.89189189],
       [ 98.        ],
       [101.        ],
       [103.        ],
       [ 99.        ],
       [100.        ],
       [ 98.        ],
       [103.        ],
       [ 98.        ],
       [101.        ],
       [103.        ],
       [100.        ],
       [ 99.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [100.89189189],
       [103.        ],
       [ 99.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [ 99.        ],
       [100.89189189],
       [102.        ],
       [103.        ],
       [104.        ],
       [ 99.        ],
       [ 98.        ],
       [ 99.        ],
       [ 98.        ],
       [ 98.        ],
       [100.89189189],
       [100.89189189],
       [101.        ],
       [ 98.        ],
       [100.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [103.        ],
       [104.        ],
       [101.        ],
       [101.        ],
       [104.        ],
       [100.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [104.        ],
       [102.        ],
       [104.        ],
       [102.        ],
       [ 98.        ],
       [103.        ],
       [100.89189189],
       [ 99.        ],
       [101.        ],
       [104.        ],
       [100.        ]])

In [26]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

# also the test data
x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [27]:
x_train_cough

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.]])

In [32]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

In [34]:
# also the test data
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])

In [35]:
x_train_gender_city.shape

(80, 4)

In [36]:
# Extracting Age
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values

In [37]:
# also the test data
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

In [38]:
x_train_age.shape

(80, 1)

In [39]:
x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)

In [40]:
# also the test data
x_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

In [41]:
x_train_transformed.shape

(80, 7)

# tranformer used

In [50]:
from sklearn.compose import ColumnTransformer

In [51]:
# idher hm remainder='passthrough' ya 'drop' likhty hn jo ka bch jany waly columns hoty hn ya tu unkp drop ya passthrough kr diya jarta ha

In [52]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [53]:
transformer.fit_transform(x_train).shape

(80, 7)

In [54]:
transformer.transform(x_test).shape

(20, 7)